_target_: encoder_extended.GemNetTEncoderExt
hidden_size: 128
num_targets: $(model.residual_latent_dim)
max_neighbors: ${model.max_neighbors}
radius: ${model.radius}
scale_file: ${oc.env:PROJECT_ROOT}/source/scaling_factors/x_encoder_scaling_factors_total_dataset_CDiVAE.json