_target_: diffusion_model.DiffusionModel

# Model parameters
hidden_dim: 256
latent_dim: 256
fc_num_layers: 2
max_atoms: ${data.max_atoms}
cost_natom: 1.
cost_coord: 10.
cost_type: 1.
cost_lattice: 10.
cost_composition: 1.
cost_edge: 10.
cost_property: 1.
beta: 0.01

# Training parameters
teacher_forcing_lattice: true
teacher_forcing_max_epoch: ${data.teacher_forcing_max_epoch}
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
sigma_begin: 5.
sigma_end: 0.05
type_sigma_begin: 5.
type_sigma_end: 0.05
num_noise_level: 50
predict_property: False

# Logging and loading parameters
load_model: False
model_location: wandb
ckpt_path: ${oc.env:PROJECT_ROOT}/model_checkpoints/model-150-epochs-MFI-only.ckpt # not applicable if model is on WandB

# From which experiment the model should be loaded for continuted training, sampling and reconstruction
experiment_name_to_load: cont_training_50_100_epochs_total_dataset

# Training
run_training: true
resume_from_checkpoint: False

# Reconstruction
run_reconstruction: false
num_reconstructions: 10
reconstructions_file: reconstructions-${expname}.pickle
save_reconstructions_online: true

# Sampling
run_sampling: false
num_samples: 30
samples_file: samples-${expname}.pickle
save_samples_online: true

defaults:
  - encoder: gemnet_encoder
  - decoder: gemnet_decoder