_target_: diffusion_model.DiffusionModel

# Model parameters
hidden_dim: 256
latent_dim: 256
fc_num_layers: 1
max_atoms: ${data.max_atoms}
cost_natom: 1.
cost_coord: 10.
cost_type: 1.
cost_lattice: 10.
cost_composition: 1.
cost_edge: 10.
cost_property: 1.
beta: 0.01

# Training parameters
teacher_forcing_lattice: true
teacher_forcing_max_epoch: ${data.teacher_forcing_max_epoch}
max_neighbors: 20  # maximum number of neighbors for OTF graph bulding in decoder
radius: 7.  # maximum search radius for OTF graph building in decoder
sigma_begin: 10.
sigma_end: 0.01
type_sigma_begin: 10.
type_sigma_end: 0.01
num_noise_level: 50
predict_property: False

# Logging and loading parameters
load_model: False
model_location: local
ckpt_path: ${oc.env:PROJECT_ROOT}/model_checkpoints/model-150-epochs-MFI-only.ckpt
experiment_name_to_load: test_new_wandb_setup
run_training: true
run_reconstruction: true
reconstructions_file: reconstructions-${expname}.pickle
save_reconstructions_online: true
run_sampling: true
num_samples: 5
samples_file: samples-${expname}.pickle
save_samples_online: true

defaults:
  - encoder: gemnet_encoder
  - decoder: gemnet_decoder