_target_: decoder.GemNetTDecoder
hidden_dim_atom_emb: 32
hidden_dim_edge_emb: 128
latent_dim: ${model.total_latent_dim}
max_neighbors: ${model.max_neighbors}
radius: ${model.radius}
scale_file: ${oc.env:PROJECT_ROOT}/source/scaling_factors/cdivae_v2/pos_decoder_scaling_factors_total_dataset_CDiVAE.json